### ISSUE TITLE
難易度「かんたん」の残像がある

### ISSUE THREAD

**Issue by s1204IT** [yuukiwww/taiko-web#1]
```
Taiko-Web version: 
URL: https://taikoapp.uk/
User agent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Mobile Safari/537.36
Screen size: 468x873, outer: 468x873, ratio: 2.31
Touch enabled: true
Blur performance: 2.5ms, all images: 446ms
Page load: 1.0s
Language: ja (ja-JP, ja, en-US, en)
Audio Latency: 0ms, Video Latency: 0ms
Plugins: 
```
---
映像のように、移動前の楽曲に「かんたん」が含まれており、タッチまたはクリックで別楽曲移動した際に残像が発生します。  
矢印キーでは動作確認していないので分かりません。

https://github.com/yuukiwww/taiko-web/assets/52069677/d9b2bc77-2e4f-48cc-b05f-5fb27e162122

デバイスは、Samsung Galaxy S22  
ブラウザは、Google Chrome `124.0.6367.82` です。

**Comment by yuukiwww** [comment]
曲スキンを50%透明にしたらこうなったので多分元々の仕様ですね
0%に戻すこともできますが再度色の調整が必要になるかも知れません

**Comment by yuukiwww** [comment]
解決済み
